const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="yasirkhan9982606@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://i.postimg.cc/SN3Yfzjy/suhail.jpg?raw=true" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "ᴘᴏᴡᴇʀᴇᴅ ʙʏ ʏᴀꜱɪʀ ᴋʜᴀɴ" 


global.devs = "923211865537" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923211865537";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_10_17_05_29_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNjQsXG4gICAgICAgIDk4LFxuICAgICAgICAxMjQsXG4gICAgICAgIDE2MixcbiAgICAgICAgNjEsXG4gICAgICAgIDE2MCxcbiAgICAgICAgMTIsXG4gICAgICAgIDI1NCxcbiAgICAgICAgMjAyLFxuICAgICAgICAyNCxcbiAgICAgICAgMTQxLFxuICAgICAgICA0NSxcbiAgICAgICAgMCxcbiAgICAgICAgMTAyLFxuICAgICAgICAxMzIsXG4gICAgICAgIDEwNSxcbiAgICAgICAgMTgwLFxuICAgICAgICAxNzIsXG4gICAgICAgIDgyLFxuICAgICAgICAyMzIsXG4gICAgICAgIDEyOCxcbiAgICAgICAgMjExLFxuICAgICAgICAxMzgsXG4gICAgICAgIDE2MixcbiAgICAgICAgMTcwLFxuICAgICAgICAxNzcsXG4gICAgICAgIDE3MCxcbiAgICAgICAgMTk5LFxuICAgICAgICA4MCxcbiAgICAgICAgMjMzLFxuICAgICAgICAzNyxcbiAgICAgICAgMTAyXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDEyLFxuICAgICAgICAyMzMsXG4gICAgICAgIDUsXG4gICAgICAgIDY0LFxuICAgICAgICA2MixcbiAgICAgICAgMjAyLFxuICAgICAgICA1NixcbiAgICAgICAgMTI4LFxuICAgICAgICA0MyxcbiAgICAgICAgMjksXG4gICAgICAgIDE1NyxcbiAgICAgICAgMTI4LFxuICAgICAgICAxMCxcbiAgICAgICAgMTIyLFxuICAgICAgICAyMTgsXG4gICAgICAgIDYxLFxuICAgICAgICAyMDUsXG4gICAgICAgIDkzLFxuICAgICAgICA1NyxcbiAgICAgICAgMTM5LFxuICAgICAgICAxOTcsXG4gICAgICAgIDE0OCxcbiAgICAgICAgMTY2LFxuICAgICAgICAxNjgsXG4gICAgICAgIDE5OCxcbiAgICAgICAgMTcsXG4gICAgICAgIDE2OCxcbiAgICAgICAgMTksXG4gICAgICAgIDc1LFxuICAgICAgICAyMjQsXG4gICAgICAgIDE3OCxcbiAgICAgICAgMTZcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIxNixcbiAgICAgICAgMjksXG4gICAgICAgIDM4LFxuICAgICAgICA0MCxcbiAgICAgICAgMTU0LFxuICAgICAgICAyMixcbiAgICAgICAgNyxcbiAgICAgICAgNzcsXG4gICAgICAgIDU5LFxuICAgICAgICA2OCxcbiAgICAgICAgMTgzLFxuICAgICAgICAxNTIsXG4gICAgICAgIDM0LFxuICAgICAgICA5NCxcbiAgICAgICAgODksXG4gICAgICAgIDEwOSxcbiAgICAgICAgMzQsXG4gICAgICAgIDIwMyxcbiAgICAgICAgOTAsXG4gICAgICAgIDYwLFxuICAgICAgICAyMDcsXG4gICAgICAgIDIxLFxuICAgICAgICA4MCxcbiAgICAgICAgMjcsXG4gICAgICAgIDE5MyxcbiAgICAgICAgMTIzLFxuICAgICAgICAxMDUsXG4gICAgICAgIDQ5LFxuICAgICAgICAxMTUsXG4gICAgICAgIDI4LFxuICAgICAgICA4OSxcbiAgICAgICAgODJcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjAxLFxuICAgICAgICA1NSxcbiAgICAgICAgNTAsXG4gICAgICAgIDcxLFxuICAgICAgICAyMzYsXG4gICAgICAgIDUsXG4gICAgICAgIDE5NCxcbiAgICAgICAgMzYsXG4gICAgICAgIDEzOCxcbiAgICAgICAgNjksXG4gICAgICAgIDE5MyxcbiAgICAgICAgNzQsXG4gICAgICAgIDI0NCxcbiAgICAgICAgMTI1LFxuICAgICAgICA4MCxcbiAgICAgICAgMjExLFxuICAgICAgICAxMCxcbiAgICAgICAgNzgsXG4gICAgICAgIDIyNyxcbiAgICAgICAgMjI3LFxuICAgICAgICAxMDksXG4gICAgICAgIDE2NCxcbiAgICAgICAgNjMsXG4gICAgICAgIDEwNyxcbiAgICAgICAgMjM5LFxuICAgICAgICA3OSxcbiAgICAgICAgMzYsXG4gICAgICAgIDIsXG4gICAgICAgIDE2MixcbiAgICAgICAgNjIsXG4gICAgICAgIDExMCxcbiAgICAgICAgMjhcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE2OCxcbiAgICAgICAgMjI1LFxuICAgICAgICAyNTIsXG4gICAgICAgIDE2NyxcbiAgICAgICAgMTQxLFxuICAgICAgICAxMjEsXG4gICAgICAgIDEyMCxcbiAgICAgICAgNTQsXG4gICAgICAgIDE2MCxcbiAgICAgICAgMTksXG4gICAgICAgIDE0MyxcbiAgICAgICAgNDYsXG4gICAgICAgIDE0NixcbiAgICAgICAgMjI5LFxuICAgICAgICAxNyxcbiAgICAgICAgMTMxLFxuICAgICAgICAxNDYsXG4gICAgICAgIDEzMCxcbiAgICAgICAgNDcsXG4gICAgICAgIDIwLFxuICAgICAgICA4NyxcbiAgICAgICAgNDEsXG4gICAgICAgIDI0OSxcbiAgICAgICAgMTAxLFxuICAgICAgICAxNDksXG4gICAgICAgIDgsXG4gICAgICAgIDIyOSxcbiAgICAgICAgNTksXG4gICAgICAgIDIxNCxcbiAgICAgICAgMCxcbiAgICAgICAgMjI5LFxuICAgICAgICA5M1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMzUsXG4gICAgICAgIDczLFxuICAgICAgICA1MSxcbiAgICAgICAgMyxcbiAgICAgICAgMCxcbiAgICAgICAgMjA3LFxuICAgICAgICA4OSxcbiAgICAgICAgOTMsXG4gICAgICAgIDUxLFxuICAgICAgICAyMDksXG4gICAgICAgIDIzMyxcbiAgICAgICAgMjMsXG4gICAgICAgIDEwMSxcbiAgICAgICAgMTAwLFxuICAgICAgICAzMyxcbiAgICAgICAgOTcsXG4gICAgICAgIDEwNixcbiAgICAgICAgNzMsXG4gICAgICAgIDE5LFxuICAgICAgICAyMDMsXG4gICAgICAgIDIzOSxcbiAgICAgICAgMTkxLFxuICAgICAgICAxNDIsXG4gICAgICAgIDE1NyxcbiAgICAgICAgMjU1LFxuICAgICAgICA5MSxcbiAgICAgICAgMTYxLFxuICAgICAgICAxNzksXG4gICAgICAgIDE4NixcbiAgICAgICAgMTU4LFxuICAgICAgICAzLFxuICAgICAgICA1OVxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA4LFxuICAgICAgICAgIDE4LFxuICAgICAgICAgIDIwMCxcbiAgICAgICAgICAxNjAsXG4gICAgICAgICAgMjcsXG4gICAgICAgICAgMjI3LFxuICAgICAgICAgIDExNSxcbiAgICAgICAgICAyNyxcbiAgICAgICAgICAxODIsXG4gICAgICAgICAgMTEwLFxuICAgICAgICAgIDEwOCxcbiAgICAgICAgICA1NixcbiAgICAgICAgICAzNCxcbiAgICAgICAgICAxNTksXG4gICAgICAgICAgMjAzLFxuICAgICAgICAgIDIyLFxuICAgICAgICAgIDEwNyxcbiAgICAgICAgICAxNzQsXG4gICAgICAgICAgMTE0LFxuICAgICAgICAgIDE2NSxcbiAgICAgICAgICAyNDAsXG4gICAgICAgICAgMTkyLFxuICAgICAgICAgIDczLFxuICAgICAgICAgIDgzLFxuICAgICAgICAgIDI1MCxcbiAgICAgICAgICAxOCxcbiAgICAgICAgICAxOTUsXG4gICAgICAgICAgMTMyLFxuICAgICAgICAgIDIxNSxcbiAgICAgICAgICAxNzksXG4gICAgICAgICAgNDQsXG4gICAgICAgICAgNzdcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNTYsXG4gICAgICAgICAgNzcsXG4gICAgICAgICAgNzcsXG4gICAgICAgICAgMjAzLFxuICAgICAgICAgIDE5MixcbiAgICAgICAgICAxNDMsXG4gICAgICAgICAgNTYsXG4gICAgICAgICAgMTc2LFxuICAgICAgICAgIDkwLFxuICAgICAgICAgIDE5NixcbiAgICAgICAgICA2MSxcbiAgICAgICAgICAxNjYsXG4gICAgICAgICAgOTEsXG4gICAgICAgICAgNTksXG4gICAgICAgICAgMjQzLFxuICAgICAgICAgIDE2OSxcbiAgICAgICAgICAyOSxcbiAgICAgICAgICAyMTYsXG4gICAgICAgICAgMTQ4LFxuICAgICAgICAgIDE4MixcbiAgICAgICAgICAyMTUsXG4gICAgICAgICAgMTczLFxuICAgICAgICAgIDMsXG4gICAgICAgICAgMTM0LFxuICAgICAgICAgIDE3MyxcbiAgICAgICAgICAyNDgsXG4gICAgICAgICAgMTQ3LFxuICAgICAgICAgIDEzNCxcbiAgICAgICAgICAxMTIsXG4gICAgICAgICAgNzAsXG4gICAgICAgICAgMTcxLFxuICAgICAgICAgIDE4XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9LFxuICAgIFwic2lnbmF0dXJlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgODYsXG4gICAgICAgIDIwMCxcbiAgICAgICAgMjU0LFxuICAgICAgICA4OCxcbiAgICAgICAgMTgxLFxuICAgICAgICA1MCxcbiAgICAgICAgMjAwLFxuICAgICAgICAyNTIsXG4gICAgICAgIDc1LFxuICAgICAgICAxOTUsXG4gICAgICAgIDgwLFxuICAgICAgICAxNDcsXG4gICAgICAgIDEyMixcbiAgICAgICAgMjQ0LFxuICAgICAgICAyNyxcbiAgICAgICAgMjQ5LFxuICAgICAgICAxMjYsXG4gICAgICAgIDE1NCxcbiAgICAgICAgMjUsXG4gICAgICAgIDI0MCxcbiAgICAgICAgMjUsXG4gICAgICAgIDIxMyxcbiAgICAgICAgMjAyLFxuICAgICAgICA4MCxcbiAgICAgICAgMTU2LFxuICAgICAgICAyMDgsXG4gICAgICAgIDE5NixcbiAgICAgICAgMTM1LFxuICAgICAgICA5MSxcbiAgICAgICAgMSxcbiAgICAgICAgMTU5LFxuICAgICAgICA4NyxcbiAgICAgICAgNjAsXG4gICAgICAgIDE4OCxcbiAgICAgICAgMjM3LFxuICAgICAgICAxNzAsXG4gICAgICAgIDExNyxcbiAgICAgICAgMjUyLFxuICAgICAgICAyMDcsXG4gICAgICAgIDE5NSxcbiAgICAgICAgODQsXG4gICAgICAgIDIyOSxcbiAgICAgICAgNDYsXG4gICAgICAgIDExNyxcbiAgICAgICAgMTE0LFxuICAgICAgICAxMTksXG4gICAgICAgIDI1MyxcbiAgICAgICAgMTU3LFxuICAgICAgICAyNTQsXG4gICAgICAgIDExLFxuICAgICAgICA0OSxcbiAgICAgICAgOTUsXG4gICAgICAgIDMsXG4gICAgICAgIDM1LFxuICAgICAgICAyMjEsXG4gICAgICAgIDE4OSxcbiAgICAgICAgMTU4LFxuICAgICAgICA2MCxcbiAgICAgICAgMTM3LFxuICAgICAgICAxOTUsXG4gICAgICAgIDEyNyxcbiAgICAgICAgMjcsXG4gICAgICAgIDgwLFxuICAgICAgICAxMjhcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDk2LFxuICBcImFkdlNlY3JldEtleVwiOiBcImUvNmpHSGYvY1hncndMbTdyS3FvNnJwTDFlaXNkZ1NUbVFpeURFRUlwMkU9XCIsXG4gIFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6IFtcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiOTIzMjExODY1NTM3QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCIwMzY5Q0ZGNzcwNUU1QkU0NUY3NUZENTUzNjA4NkNGOFwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MTY5Nzc4MTZcbiAgICB9LFxuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCI5MjMyMTE4NjU1MzdAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjM4RkY3MDZBM0JEOUQ2OTJFMEQyNzAyQzM1QTk3ODJFXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcxNjk3NzgxNlxuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjkyMzIxMTg2NTUzN0BzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiNDM1RThEMjJEMkEzNEFBQTFBMTNCRjBBNTgxMzIxRDlcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzE2OTc3ODIxXG4gICAgfVxuICBdLFxuICBcIm5leHRQcmVLZXlJZFwiOiAzMSxcbiAgXCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZFwiOiAzMSxcbiAgXCJhY2NvdW50U3luY0NvdW50ZXJcIjogMSxcbiAgXCJhY2NvdW50U2V0dGluZ3NcIjoge1xuICAgIFwidW5hcmNoaXZlQ2hhdHNcIjogZmFsc2VcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcIlhITGV4VFRNUW0tWExlYXZoNEJXb2dcIixcbiAgXCJwaG9uZUlkXCI6IFwiNzcwNzY4YzItOTRjNC00ODJlLWFiNDAtOTQ1OWViNjcyNTk2XCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDIyOSxcbiAgICAgIDEzLFxuICAgICAgNDMsXG4gICAgICAyMTcsXG4gICAgICA0NyxcbiAgICAgIDg4LFxuICAgICAgMTcsXG4gICAgICAxODksXG4gICAgICAxOTMsXG4gICAgICAxNzMsXG4gICAgICAxMTQsXG4gICAgICAxMjQsXG4gICAgICAyMixcbiAgICAgIDE0NSxcbiAgICAgIDIxOCxcbiAgICAgIDE2NCxcbiAgICAgIDc4LFxuICAgICAgMTczLFxuICAgICAgMTk5LFxuICAgICAgMjUzXG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogZmFsc2UsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICA5OCxcbiAgICAgIDIzNixcbiAgICAgIDY2LFxuICAgICAgMTQ5LFxuICAgICAgMjE4LFxuICAgICAgMjMxLFxuICAgICAgODQsXG4gICAgICAxNDgsXG4gICAgICAyMzEsXG4gICAgICA1NyxcbiAgICAgIDI4LFxuICAgICAgMTk5LFxuICAgICAgMTgwLFxuICAgICAgNDIsXG4gICAgICA1NixcbiAgICAgIDg3LFxuICAgICAgMTQxLFxuICAgICAgMjU0LFxuICAgICAgMjIxLFxuICAgICAgMTg0XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDTDM2Z05BQ0VKT0IzTElHR0FFZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJpWFFtYnNudjVUNmY4emZ2OTJsN0xpa0FBbkEyV2tlRUprUFo2WWUrV2lZPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcInJZYXpwdXNnS2hJVUd4cm9NSVpic2w3ZGZiT0U0T3dMSnBxVWdaay9hYW12SFhOMnNxQXdyTjdQSkdEL0dTSllyZ1ZGT1FyUnFWT2xYeUlXajBuR0JBPT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcIlJCOW9SS3Jub2VCNW9BdUppaXRteXhORTE3UVo3bkhoUHIvZ2lqUno2aTBRbzZlUHNVZUcrazRzbXZ0ZXlObmJSUUxqQmp6elpJbFM0aExqc2xyTmhnPT1cIlxuICB9LFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiOTIzMjExODY1NTM3OjlAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcImxpZFwiOiBcIjIwMjIzMzI0OTU1MDU1Njo5QGxpZFwiLFxuICAgIFwibmFtZVwiOiBcIlNhaXJhXCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCI5MjMyMTE4NjU1Mzc6OUBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDEzNyxcbiAgICAgICAgICAxMTYsXG4gICAgICAgICAgMzgsXG4gICAgICAgICAgMTEwLFxuICAgICAgICAgIDIwMSxcbiAgICAgICAgICAyMzksXG4gICAgICAgICAgMjI5LFxuICAgICAgICAgIDYyLFxuICAgICAgICAgIDE1OSxcbiAgICAgICAgICAyNDMsXG4gICAgICAgICAgNTUsXG4gICAgICAgICAgMjM5LFxuICAgICAgICAgIDI0NyxcbiAgICAgICAgICAxMDUsXG4gICAgICAgICAgMTIzLFxuICAgICAgICAgIDQ2LFxuICAgICAgICAgIDQxLFxuICAgICAgICAgIDAsXG4gICAgICAgICAgMixcbiAgICAgICAgICAxMTIsXG4gICAgICAgICAgNTQsXG4gICAgICAgICAgOTAsXG4gICAgICAgICAgNzEsXG4gICAgICAgICAgMTMyLFxuICAgICAgICAgIDM4LFxuICAgICAgICAgIDY3LFxuICAgICAgICAgIDIxNyxcbiAgICAgICAgICAyMzMsXG4gICAgICAgICAgMTM1LFxuICAgICAgICAgIDE5MCxcbiAgICAgICAgICA5MCxcbiAgICAgICAgICAzOFxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzE2OTc3ODE1LFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBUE5yXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFQTmsuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJzVzNWcE9rMnlYSVZoV3lZVmVDMEYyZnB6YlJrUHpiUEtuREdsRmZwdTFNPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjcwNDY1ODc0NCxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzEzMjg2MzA4NDM5XCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBUE5tLmpzb24iOiAie1wia2V5RGF0YVwiOlwiZVM4SEJqcmVRVU1hWkhjZXBFVlZZck5GMVRQQ2VLZ0RMbUI5RmNFeVptZz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjo3MDQ2NTg3NDQsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMTcxNDY1MjY4MDkyNVwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQVBObi5qc29uIjogIntcImtleURhdGFcIjpcIjFNWFAvVUZmTnZvM1d2Rm16aWgya1R5T29QejBUTUlONlVkNXE5K2Q4aHc9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6NzA0NjU4NzQ0LFwiY3VycmVudEluZGV4XCI6NSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFQTm8uanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJlMXkrL3pVTHNmRlp4d1I1WGUrOWRIYlZqNmZ5bVRRM1ZLclFvWDJMaVVVPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjcwNDY1ODc0NCxcImN1cnJlbnRJbmRleFwiOjUsXCJkZXZpY2VJbmRleGVzXCI6WzBdfSxcInRpbWVzdGFtcFwiOlwiMTcxNTA4NDYxMTY1NVwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQVBOcC5qc29uIjogIntcImtleURhdGFcIjpcIjExOWU1Y1ZxSzFNZFF3cC9JKzZuK1BWdWRXWDllQjVnK3NjQTNCL0NxaUE9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6NzA0NjU4NzQ1LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMF19LFwidGltZXN0YW1wXCI6XCIxNzE2OTc1MzY4OTQ0XCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBUE5xLmpzb24iOiAie1wia2V5RGF0YVwiOlwibnNhby9ZZFNab1dvSXhZNkZ1UDc5WTBwVmlhZ0JNblcxaFdUajg3ZjJzND1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjo3MDQ2NTg3NDcsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MTY5NzU1NDMzMzRcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFQTnIuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJsdFRnd3ZtTEFwTzJURU50WDlVbTMrSUhIMkJIMkhsUmM2ZnJtVkFvSUNrPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjcwNDY1ODc0OCxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzE2OTc3ODA4NTYxXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBWUFBUE5sLmpzb24iOiAie1wia2V5RGF0YVwiOlwieGd2ZXhhanlxVGExclNpUW5UQmtOUkIxUmNNTUVialFuVEtkNEkreFM0TT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjo3MDQ2NTg3NDQsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDZdfSxcInRpbWVzdGFtcFwiOlwiMTcxNDE0MTA3MTAxM1wifSIKfQ=="  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.7",
  caption : global.caption || "" , // ```『 𝐶𝑟𝑒𝑎𝑡𝑒𝑑 𝐵𝑦 𝑌𝑎𝑠𝑖𝑟 』```", //*『Contact』*\n Whatsapp 03186385943"),
 
  author : process.env.PACK_AUTHER|| "",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "Ꭹꮧꮥꭵꮢ-Ꮶꮒꮧꮑ",
  ownername:process.env.OWNER_NAME|| "ɪᴛ' x ʏᴀꜱɪʀ",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "private",
  LANG: ( process.env.THEME ||  "ʏᴀꜱɪʀ"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
